### ISSUE TITLE
Changing scenario 4 model to be in petrinet format 

### ISSUE THREAD

**Issue by sabinala** [gyorilab/mira#291]
Currently, only petrinet models can be uploaded to Terarium, so I am using [this](https://github.com/gyorilab/mira/blob/main/notebooks/hackathon_2024.02/scenario4/scenario4.ipynb) notebook to change the output format from regnet to petrinet.

**Comment by sabinala** [comment]
Ok that would be great actually!

**Comment by sabinala** [comment]
Thanks!

**Comment by bgyori** [comment]
Available here: https://github.com/gyorilab/mira/tree/main/notebooks/hackathon_2024.02/scenario4
