### ISSUE TITLE
Inconsistent colours used when plotting `TemplateModelDelta`

### ISSUE THREAD

**Issue by liunelson** [gyorilab/mira#307]
`TemplateModelDelta.__init__` and `TemplateModelDelta.for_jupyter` use different colours for the first, second, and merged models.

https://github.com/gyorilab/mira/blob/main/mira/metamodel/comparison.py#L402

vs. 

https://github.com/gyorilab/mira/blob/main/mira/metamodel/comparison.py#L676

**Comment by kkaris** [comment]
I completely missed this issue! Sorry about that!

PR submitted.
