### ISSUE TITLE
[BUG]: Some annotations are missed by `template_model_from_amr_json`

### ISSUE THREAD

**Issue by liunelson** [gyorilab/mira#341]
`template_model_from_amr_json` only reads `name, description` from an AMR JSON's annotation section.
https://github.com/gyorilab/mira/blob/e468059089681c7cd457acc51821b5bd1074df04/mira/sources/amr/petrinet.py#L219

It should read all fields (e.g. `license, locations, references, ...`) described in here:
https://github.com/gyorilab/mira/blob/e468059089681c7cd457acc51821b5bd1074df04/mira/metamodel/template_model.py#L192

**Comment by bgyori** [comment]
Fixed in #340
