### ISSUE TITLE
[BUG] Changing concepts with `get_concepts_name_map()` does not update the concepts in a model's `initials`

### ISSUE THREAD

**Issue by liunelson** [gyorilab/mira#371]
I updated the `context` field of the concepts from `model.get_concepts_name_map()`. However, those changes do not propagate to the concepts from `model.initials`. I expected that there is a common 'pool' of concepts used by the `model.templates` and the `model.initials` since they both refer to the same state variables and I'd only need to update their context once.

**Comment by bgyori** [comment]
No, each Concept instance you see in the TemplateModel is a different object instance. This is by design, and on purpose, so one cannot change a single Concept by reference and expect other Concept instances that happen to match.
