### ISSUE TITLE
SBML initialAmount is not supported, but initialConcentration is

### ISSUE THREAD

**Issue by djinnome** [gyorilab/mira#374]
Hi folks,

If an SBML model contains `initialAmount` instead of `initialConcentration`, then MIRA cannot read in the intial amount.

 From the [libsbml specification](https://sbml.org/software/libsbml/5.18.0/docs/formatted/c-api/class_species__t.html):

> The optional attributes "initialAmount" and "initialConcentration", both having a data type of double, can be used to set the initial quantity of the species in the compartment where the species is located. These attributes are mutually exclusive; i.e., only one can have a value on any given instance of a [Species_t](https://sbml.org/software/libsbml/5.18.0/docs/formatted/c-api/class_species__t.html) object. Missing "initialAmount" and "initialConcentration" values implies that their values either are unknown, or to be obtained from an external source, or determined by an [InitialAssignment_t](https://sbml.org/software/libsbml/5.18.0/docs/formatted/c-api/class_initial_assignment__t.html) or other SBML construct elsewhere in the model.

Until MIRA supports `initialAmount`, here is a workaround:

```python
def update_SBML_for_MIRA(original_sbml_file, updated_sbml_file):
    """Updates the SBML file to ensure that the species name, initial concentrations, and has_only_substance_units are set."""
    
    # Read the SBML file
    document = libsbml.readSBMLFromFile(original_sbml_file)
    model = document.getModel()
    
    for species in model.getListOfSpecies():
        # Check if species has a valid ID
        if not species.isSetId() or not species.getId():
            raise ValueError("A species found without a valid ID.")
        
        # Set the species name to the ID if the name is not valid
        if not species.isSetName() or not species.getName():
            species.setName(species.getId())
        
        # Set initial concentration using initial amount if not already valid
        if not species.isSetInitialConcentration() or species.getInitialConcentration() <= 0:
            if species.isSetInitialAmount() and species.getInitialAmount() >= 0:
                species.setInitialConcentration(species.getInitialAmount())
            else:
                raise ValueError(f"Species '{species.getId()}' does not have a valid initial concentration or amount.")
        
        # Set has_only_substance_units to False
        species.setHasOnlySubstanceUnits(False)
    
    # Write the updated SBML file
    libsbml.writeSBMLToFile(document, updated_sbml_file)
 ```

**Comment by bgyori** [comment]
@djinnome is there a specific SBML file which uses initialAmount that we could look at to test against?
