### ISSUE TITLE
[BUG]: state variables/concepts lose their description in `template_model_to_petrinet_json`

### ISSUE THREAD

**Issue by liunelson** [gyorilab/mira#389]
`template_model_to_petrinet_json` is lossy when it comes to the description of the state variable concepts.
https://github.com/gyorilab/mira/blob/0eec1320569663728e609fc498003c9d3ca553f3/mira/modeling/amr/petrinet.py#L349

The PetriNet AMR JSON schema supports state variable descriptions; so, concept description should probably be preserved in the JSON.

Example:
* as a TemplateModel JSON:
https://github.com/liunelson/mira/blob/nliu/experiment/notebooks/nliu/data/monthly_demo_202410/prob5_test.json
* as a AMR
https://github.com/liunelson/mira/blob/nliu/experiment/notebooks/nliu/data/monthly_demo_202410/Prob%205%20Model%20A%20(1%2C992%20counties).json

**Comment by nanglo123** [comment]
I believe I fixed the issue and will open a PR.

Here is an example of an petrinet amr that was created from loading in the template model json you linked (the first file) and exporting it as a petrinet amr. As you can see concept descriptions are now propogated. 

https://github.com/nanglo123/mira/blob/42f9725fc23b5f8d0d64b46850a1af5b57ccfd01/mira/modeling/amr/propogated_concept_description_petrinet.json
